// Code generated by "stringer -type=ServerState -trimprefix=Server -output=enums_string.go"; DO NOT EDIT.

package pickaxx

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Starting-0]
	_ = x[Started-1]
	_ = x[Stopping-2]
	_ = x[Stopped-3]
	_ = x[Unknown-4]
}

const _ServerState_name = "StartingStartedStoppingStoppedUnknown"

var _ServerState_index = [...]uint8{0, 8, 15, 23, 30, 37}

func (i ServerState) String() string {
	if i < 0 || i >= ServerState(len(_ServerState_index)-1) {
		return "ServerState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ServerState_name[_ServerState_index[i]:_ServerState_index[i+1]]
}
