name: Build & Test

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: [self-hosted]
    steps:

    - name: Setup
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code
      uses: actions/checkout@v2

    - name: Fetch module dependencies
      run: |
        go get -v -t -d ./...

    - name: Compile & build
      run: go build -v ./...
    - name: Run tests
      run: go test -race -v ./...
