name: Build & Test

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Build Image
      uses: docker/build-push-action@v1
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: false
        tags: pickaxx:latest
